apiVersion: v1
kind: Pod
metadata:
  name: initial-admin-password
  namespace: jenkins
spec:
  containers:
  - name: initial-admin-password
    image: busybox
    command:
      - "cat"
    args:
      - "/var/jenkins_home/secrets/initialAdminPassword"
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-home
  restartPolicy: OnFailure
  volumes:
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: jenkins-home
